debug: true
server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/demo
    username: demo
    password: demo_pwd